services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - '5001:5001'
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis
    volumes:
      - ./backend/prisma:/app/prisma
      - ./backend/entrypoint.sh:/app/entrypoint.sh
    networks:
      - expearti-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - '5002:5002'
    environment:
      - NODE_ENV=production
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - expearti-net

  db:
    image: postgres:14-alpine
    container_name: db
    restart: always
    env_file:
      - ./backend/.env
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-budzetownik}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - expearti-net

  redis:
    image: redis:7-alpine
    container_name: redis
    volumes:
      - redis_data:/data
    networks:
      - expearti-net

volumes:
  db_data:
  redis_data:

networks:
  expearti-net:
    driver: bridge