{{- if .Values.backend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "budzetownik-chart.fullname" . }}-backend
  labels:
    {{- include "budzetownik-chart.backend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.backend.enabled }}
  replicas: {{ .Values.backend.replicaCount }}
  {{- end }}
  strategy:
    {{- toYaml .Values.backend.strategy | nindent 4 }}
  revisionHistoryLimit: {{ .Values.backend.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "budzetownik-chart.backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "budzetownik-chart.backend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "budzetownik-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.backend.name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.global.imageRegistry }}{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: {{ .Values.backend.service.name }}
              containerPort: {{ .Values.backend.service.targetPort }}
              protocol: TCP
          
          {{- if .Values.backend.healthChecks.enabled }}
          livenessProbe:
            {{- toYaml .Values.backend.healthChecks.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.backend.healthChecks.readinessProbe | nindent 12 }}
          {{- end }}
          
          env:
            - name: DATABASE_URL
              value: {{ include "budzetownik-chart.databaseUrl" . | quote }}
            {{- range $key, $value := .Values.backend.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          
          envFrom:
            {{- if .Values.config }}
            - configMapRef:
                name: {{ include "budzetownik-chart.fullname" . }}-config
            {{- end }}
            - secretRef:
                name: {{ include "budzetownik-chart.fullname" . }}-postgresql-secret
          
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
          
          {{- if .Values.securityContext.readOnlyRootFilesystem }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: var-cache
              mountPath: /var/cache
          {{- end }}
      
      {{- if .Values.securityContext.readOnlyRootFilesystem }}
      volumes:
        - name: tmp
          emptyDir: {}
        - name: var-cache
          emptyDir: {}
      {{- end }}
      
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
---
{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "budzetownik-chart.fullname" . }}-frontend
  labels:
    {{- include "budzetownik-chart.frontend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.frontend.enabled }}
  replicas: {{ .Values.frontend.replicaCount }}
  {{- end }}
  strategy:
    {{- toYaml .Values.frontend.strategy | nindent 4 }}
  revisionHistoryLimit: {{ .Values.frontend.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "budzetownik-chart.frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "budzetownik-chart.frontend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "budzetownik-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.frontend.name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.global.imageRegistry }}{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.targetPort }}
              protocol: TCP
          
          {{- if .Values.frontend.healthChecks.enabled }}
          livenessProbe:
            {{- toYaml .Values.frontend.healthChecks.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.frontend.healthChecks.readinessProbe | nindent 12 }}
          {{- end }}
          
          env:
            {{- range $key, $value := .Values.frontend.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          
          {{- if .Values.config }}
          envFrom:
            - configMapRef:
                name: {{ include "budzetownik-chart.fullname" . }}-config
          {{- end }}
          
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          
          {{- if .Values.securityContext.readOnlyRootFilesystem }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: next-cache
              mountPath: /.next
          {{- end }}
      
      {{- if .Values.securityContext.readOnlyRootFilesystem }}
      volumes:
        - name: tmp
          emptyDir: {}
        - name: next-cache
          emptyDir: {}
      {{- end }}
      
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
