{{- if and .Values.global.environment (eq .Values.global.environment "production") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "budzetownik-chart.fullname" . }}-security-headers
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "budzetownik-chart.labels" . | nindent 4 }}
data:
  X-Frame-Options: "DENY"
  X-Content-Type-Options: "nosniff"
  X-XSS-Protection: "1; mode=block"
  Strict-Transport-Security: "max-age=31536000; includeSubDomains; preload"
  Content-Security-Policy: "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self'"
  Referrer-Policy: "strict-origin-when-cross-origin"
  Permissions-Policy: "geolocation=(), microphone=(), camera=()"
{{- end }}
