global:
  environment: production

backend:
  replicaCount: 3

  image:
    tag: 'prod'

  service:
    type: ClusterIP
    port: 5001

  env:
    NODE_ENV: production
    LOG_LEVEL: warn

  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi

  healthChecks:
    enabled: true
    livenessProbe:
      httpGet:
        path: /wakacyjne/health
        port: http
      initialDelaySeconds: 60
      periodSeconds: 30
      timeoutSeconds: 10
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /wakacyjne/health
        port: http
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3

frontend:
  replicaCount: 3

  image:
    tag: 'prod'

  service:
    type: ClusterIP
    port: 80
    targetPort: 5002

  env:
    NODE_ENV: production
    NEXT_PUBLIC_API_URL: https://api.budzetownik.com

  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 800m
      memory: 1Gi

  healthChecks:
    enabled: true
    livenessProbe:
      httpGet:
        path: /
        port: 5002
      initialDelaySeconds: 30
      periodSeconds: 15
      timeoutSeconds: 5
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /
        port: 5002
      initialDelaySeconds: 15
      periodSeconds: 10
      timeoutSeconds: 3
      failureThreshold: 3

database:
  postgresql:
    enabled: false
  custom:
    enabled: true
    image:
      repository: postgres
      tag: '13'
    persistence:
      enabled: true
      size: 10Gi
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 2000m
        memory: 2Gi

databaseJobs:
  migrate:
    enabled: true
    image:
      tag: 'prod'
  seed:
    enabled: false

secrets:
  postgresql:
    existingSecret: 'postgres-prod-credentials'
    userKey: 'username-prod'
    passwordKey: 'password-prod'
    POSTGRES_USER: ''
    POSTGRES_PASSWORD: ''

ingress:
  enabled: true
  className: 'nginx'
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/ssl-protocols: 'TLSv1.2 TLSv1.3'
    nginx.ingress.kubernetes.io/rate-limit-connections: '10'
    nginx.ingress.kubernetes.io/rate-limit-requests-per-second: '20'
    nginx.ingress.kubernetes.io/add-headers: 'budzetownik-prod/security-headers'
  hosts:
    - host: budzetownik.com
      paths:
        - path: /
          pathType: Prefix
          service: frontend
        - path: /api
          pathType: Prefix
          service: backend
  tls:
    - secretName: budzetownik-tls
      hosts:
        - budzetownik.com

autoscaling:
  backend:
    enabled: true
    minReplicas: 3
    maxReplicas: 20
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80

  frontend:
    enabled: true
    minReplicas: 3
    maxReplicas: 15
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000

networkPolicy:
  enabled: true
