apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend-replicaset
  labels:
    app: budzetownik
    tier: frontend
    controller: replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: budzetownik
      tier: frontend
  template:
    metadata:
      labels:
        app: budzetownik
        tier: frontend
        created-by: replicaset
    spec:
      containers:
        - name: frontend
          image: budzetownik-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 400m
              memory: 512Mi
