name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: budzetownik_user
          POSTGRES_PASSWORD: budzetownik_password
          POSTGRES_DB: budzetownik
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U budzetownik_user -d budzetownik"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DATABASE_URL: postgresql://budzetownik_user:budzetownik_password@localhost:5432/budzetownik
      DATABASE_URL_TEST: postgresql://budzetownik_user:budzetownik_password@localhost:5432/budzetownik_test

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Check commit name
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

      - name: Run prettier
        run: npm run format:check
        if: always()

      - name: Run Lint
        run: npm run lint
        if: always()

      - name: Check types
        run: npm run typecheck
        if: always()

      - name: Generate Prisma client
        run: npx prisma generate
        if: always()

      - name: Apply Prisma schema to database
        run: npx prisma migrate deploy
        if: always()

      - name: Seed database
        run: npm run seed
        if: always()

      - name: Create test database
        run: PGPASSWORD=budzetownik_password createdb -h localhost -U budzetownik_user budzetownik_test

      - name: Apply Prisma schema to test database
        run: npm run test:prepare
        if: always()

      - name: Run tests
        run: npm test
        if: always()

      - name: Run e2e tests
        run: npm run test:e2e
        if: always()

      - name: Build
        run: npm run build
        if: always()
