apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: backend-replicaset
  labels:
    app: budzetownik
    tier: backend
    controller: replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: budzetownik
      tier: backend
  template:
    metadata:
      labels:
        app: budzetownik
        tier: backend
        created-by: replicaset
    spec:
      containers:
        - name: backend
          image: budzetownik-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5001
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 400m
              memory: 512Mi
