apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: budzetownik
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: budzetownik
    tier: backend
  ports:
    - port: 5001
      targetPort: http
      protocol: TCP
      name: http
